import { ShoppingCartProvider } from '@/context/use-shopping-cart'
import './globals.css'
import { Inter } from 'next/font/google'
import { ProductsProvider } from '@/context/use-products'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <ProductsProvider>
                <ShoppingCartProvider>
                    <body>{children}</body>
                </ShoppingCartProvider>
            </ProductsProvider>
        </html>
    )
}
